version: '3.5'

services:
  app:
    hostname: api-masdiag-staging
    image: 127.0.0.1:5000/api-masdiag-staging:latest
    command: sh -c "export RAILS_MASTER_KEY=\"$$(cat /run/secrets/rails_master_key)\"; ./bin/rails s -p 3000 -b '0.0.0.0' -e staging"
    # volumes:
    #   - "/storage/rails/api-masdiag-staging/log:/app2/log"
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_ENV: staging
    secrets:
      - source: masdiagapi_staging_rails_master_key
        target: rails_master_key
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true        
        - traefik.http.middlewares.redirect-web-secure.redirectscheme.scheme=https
        - traefik.http.routers.apisandbox.middlewares=redirect-web-secure
        - traefik.http.routers.apisandbox.entrypoints=web      
        - traefik.http.routers.apisandbox.rule=Host(`apisandbox.masdiag.pl`)
        - traefik.http.routers.apisandbox-secure.tls=true
        - traefik.http.routers.apisandbox-secure.tls.certresolver=myresolver
        - traefik.http.routers.apisandbox-secure.entrypoints=websecure
        - traefik.http.routers.apisandbox-secure.rule=Host(`apisandbox.masdiag.pl`)
        - traefik.http.services.apisandbox-secure.loadbalancer.server.port=3000
        - traefik.http.services.apisandbox-secure.loadbalancer.sticky.cookie=true
        - traefik.http.services.apisandbox-secure.loadbalancer.sticky.cookie.secure=true
        - traefik.docker.network=webgateway
      # placement:
      #   constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      placement:
        constraints: 
          - node.role == worker
          - node.platform.arch == x86_64
  solid_queue:
    image: 127.0.0.1:5000/api-masdiag-staging:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_ENV: staging
    secrets:
      - source: masdiagapi_staging_rails_master_key
        target: rails_master_key
    command: sh -c "export RAILS_MASTER_KEY=\"$$(cat /run/secrets/rails_master_key)\"; bundle exec rake solid_queue:start"
    # networks:
    #   - appnet

networks:
  traefik:
    name: webgateway
    external: true

secrets:
  masdiagapi_staging_rails_master_key:
    external: true


