version: '3.5'

services:
  app:
    hostname: api-masdiag-production
    image: 127.0.0.1:5000/api-masdiag-production:latest
    # volumes:
    #   - "/storage/rails/api-masdiag-production/log:/app2/log"
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_ENV: production
    secrets:
      - source: masdiagapi_production_rails_master_key
        target: rails_master_key
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true        
        - traefik.http.middlewares.redirect-web-secure.redirectscheme.scheme=https
        - traefik.http.routers.api-masdiag.middlewares=redirect-web-secure
        - traefik.http.routers.api-masdiag.entrypoints=web      
        - traefik.http.routers.api-masdiag.rule=Host(`api.masdiag.pl`)
        - traefik.http.routers.api-masdiag-secure.tls=true
        - traefik.http.routers.api-masdiag-secure.tls.certresolver=myresolver
        - traefik.http.routers.api-masdiag-secure.entrypoints=websecure
        - traefik.http.routers.api-masdiag-secure.rule=Host(`api.masdiag.pl`)
        - traefik.http.services.api-masdiag-secure.loadbalancer.server.port=3000
        - traefik.http.services.api-masdiag-secure.loadbalancer.sticky.cookie=true
        - traefik.http.services.api-masdiag-secure.loadbalancer.sticky.cookie.secure=true
        - traefik.docker.network=webgateway
      # placement:
      #   constraints: [node.role == worker]
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
        order: stop-first
        failure_action: rollback
      placement:
        constraints: 
          - node.role == worker
          - node.platform.arch == x86_64
  solid_queue:
    image: 127.0.0.1:5000/api-masdiag-production:latest
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_ENV: production
    secrets:
      - source: masdiagapi_production_rails_master_key
        target: rails_master_key
    command: sh -c "bundle exec rake solid_queue:start"
    # networks:
    #   - appnet

networks:
  traefik:
    name: webgateway
    external: true

secrets:
  masdiagapi_production_rails_master_key:
    external: true


