version: '3.7'

services:
  app:
    image: 127.0.0.1:5000/api-masdiag-staging:latest
    hostname: api-masdiag-staging
    build:
      context: .
      args:
        RAILS_MASTER_KEY: xxxxxxxxxxxxxxxxxxxxxxx
        RAILS_ENV: staging
    expose:
      - "3000"
    restart:
        unless-stopped
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_ENV: staging
    ports:
      - "3000:3000"    


        

