default: &default
  hourly_failed_executions_checking:
    class: MasdiagRecurring::Hourly::FailedExecutionMonitoringJob
    queue: background
    args: []
    schedule: every hour
  hourly_delayed_jobs_monitoring:
    class: MasdiagRecurring::Hourly::DelayedJobsMonitoringJob
    queue: background
    args: []
    schedule: every hour
  monthly_decretion_report_job:
    class: MasdiagRecurring::Monthly::DecretionReportJob
    queue: background
    args: []
    schedule: "0 4 1 * *"
  monthly_foreign_samples_report_job:
    class: MasdiagRecurring::Monthly::ForeignSamplesReportJob
    queue: background
    args: []
    schedule: "15 4 1 * *"
  monthly_hospital_summary_job:
    class: MasdiagRecurring::Monthly::HospitalSummaryJob
    queue: background
    args: []
    schedule: "30 4 1 * *"
  monthly_ptc_summary_job:
    class: MasdiagRecurring::Monthly::PtcSummaryJob
    queue: background
    args: []
    schedule: "45 4 1 * *"
  daily_ceracreen_performance_statistic:
    class: MasdiagRecurring::Daily::CerascreenPerformanceStatisticJob
    queue: background
    args: []
    schedule: "45 6 * * *"
  daily_ceracreen_dao_declaration:
    class: MasdiagRecurring::Daily::CerascreenDaoDeclarationJob
    queue: background
    args: []
    schedule: "0 20 * * *"
  daily_delayed_samples:
    class: MasdiagRecurring::Daily::DelayedSamplesJob
    queue: background
    args: []
    schedule: "0 5 * * *"
  fftb_report_sender:
    class: MasdiagRecurring::Daily::FftbReportSenderJob
    queue: background
    args: []
    schedule: "45 5 * * *"
  hospital_samples_zipper:
    class: MasdiagRecurring::Daily::HospitalsSamplesZipperJob
    queue: background
    args: []
    schedule: "30 5 * * *"
  periodic_cleanup:
    class: MasdiagRecurring::Myjob
    queue: background
    args: [ { batch_size: 500 } ]
    schedule: every 5 minutes



development:
 <<: *default

# test:
#  <<: *default

staging:
 <<: *default

production:
 <<: *default




 