default: &default
  hourly_failed_executions_checking:
    class: MasdiagRecurring::Hourly::FailedExecutionMonitoringJob
    queue: background
    args: []
    schedule: every hour
  delayed_jobs_monitoring:
    class: MasdiagRecurring::Hourly::DelayedJobsMonitoringJob
    queue: background
    args: []
    schedule: every hour
  hourly_failed_executions_checking:
    class: MasdiagRecurring::Monthly::DecretionReportJob
    queue: background
    args: []
    schedule: "30 4 1 * *"
  periodic_cleanup:
    class: MasdiagRecurring::Myjob
    queue: background
    args: [ { batch_size: 500 } ]
    schedule: every 5 minutes    

development:
 <<: *default

# test:
#  <<: *default

staging:
 <<: *default

production:
 <<: *default